// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-D9psp2CCIad6_lLO97H_srdDln6BLE',
    appId: '1:73683543088:web:9f89e9702cb7bc984af9f5',
    messagingSenderId: '73683543088',
    projectId: 'profileapp-dcce0',
    authDomain: 'profileapp-dcce0.firebaseapp.com',
    storageBucket: 'profileapp-dcce0.firebasestorage.app',
    measurementId: 'G-9QJRNHHWPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqrCEnB6Rsmj27jQNNMMr9ri4ZV5GHGo',
    appId: '1:73683543088:android:274810b09d31a7f84af9f5',
    messagingSenderId: '73683543088',
    projectId: 'profileapp-dcce0',
    storageBucket: 'profileapp-dcce0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ4QjpNw6QArBFrxe8Neimm0hXunBLzEk',
    appId: '1:73683543088:ios:ccab1e707ce7fd804af9f5',
    messagingSenderId: '73683543088',
    projectId: 'profileapp-dcce0',
    storageBucket: 'profileapp-dcce0.firebasestorage.app',
    iosBundleId: 'com.example.profile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ4QjpNw6QArBFrxe8Neimm0hXunBLzEk',
    appId: '1:73683543088:ios:e9249ea77ce16f824af9f5',
    messagingSenderId: '73683543088',
    projectId: 'profileapp-dcce0',
    storageBucket: 'profileapp-dcce0.firebasestorage.app',
    iosBundleId: 'com.example.profile.RunnerTests',
  );
}
